### ISSUE TITLE
Crash in Xcode 9 and Swift 4

### ISSUE THREAD

**Issue by rs-georg** [jkolb/FieryCrucible#19]
Our iOS app crashes with following error:

`Simultaneous accesses to 0x60800026a990, but modification requires exclusive access.`

in the DependencyFactory class in lines 72 and 79

**Comment by jkolb** [comment]
This may be a bug in Swift 4, I don't really want to deal with Swift 4 until it is finalized later this year. If it still exists around that time then hopefully there will be more information and documentation around this new feature that would help to make finding the fix easier.

https://stackoverflow.com/questions/44776580/does-the-warning-simultaneous-accesses-to-parameter-self-really-apply-he

**Comment by rs-georg** [comment]
Thanks for your quick reply. You're right, Swift 4 support should be delayed until it's out of beta. I was just a bit surprised since it was working perfectly with beta 2.
btw: This project is great. I really like the concept and the approach to DI. Very simple, very easy and purely Swift. Great job!

**Comment by jkolb** [comment]
I went ahead and updated for Swift 4 since Xcode 9 GM is out. This crash was a problem in the code still and the tests were able to reproduce it. Luckily the fix was easy. The problem was because I was using an inout variable that was referencing properties of the class. This caused overlapping access as the inject method would also access those properties directly in some cases. I just removed the instances inout parameter and instead use the lifecycle parameter to detect which property needs to be accessed so that it can be done directly inside the method.
